In [4]:
import numpy as np

In [5]:
my_array = np.random.random((4))
my_array

array([0.56214363, 0.27266209, 0.6364846 , 0.23467782])

In [7]:
np.array(my_array)

array([0.56214363, 0.27266209, 0.6364846 , 0.23467782])

In [10]:
b = np.random.random((2,3))
b

array([[0.41950371, 0.44858205, 0.21128535],
       [0.63775981, 0.01308035, 0.42900569]])

In [11]:
b.shape

(2, 3)

In [12]:
b.size

6

In [14]:
np.random.randint(0,9,(2,3))

array([[8, 5, 5],
       [5, 7, 0]])

In [17]:
c = np.random.randint(0,9,(2,5))

In [18]:
c.size

10

In [19]:
c.shape

(2, 5)

In [21]:
np.random.randint(0,9,(4,3,2))

array([[[1, 3],
        [3, 4],
        [0, 8]],

       [[6, 7],
        [3, 5],
        [2, 0]],

       [[7, 0],
        [0, 1],
        [4, 3]],

       [[0, 0],
        [6, 7],
        [4, 4]]])

In [22]:
np.random.randint(0,9,(2,4,3,2))

array([[[[6, 1],
         [4, 2],
         [2, 2]],

        [[7, 4],
         [4, 2],
         [4, 8]],

        [[6, 7],
         [1, 5],
         [0, 3]],

        [[2, 5],
         [4, 7],
         [8, 3]]],


       [[[6, 2],
         [8, 7],
         [0, 8]],

        [[6, 8],
         [5, 6],
         [2, 3]],

        [[4, 2],
         [5, 2],
         [2, 4]],

        [[6, 2],
         [7, 4],
         [3, 8]]]])

In [26]:
d = np.random.randint(0,9,(4,3))
d

array([[5, 0, 2],
       [1, 7, 4],
       [5, 4, 5],
       [7, 8, 7]])

In [29]:
d[0]

array([5, 0, 2])

In [30]:
d[2][1]

4

In [31]:
d[2,1]

4

In [32]:
e = np.random.randint(0,20,(6,4))
e

array([[17,  5, 19,  6],
       [17, 13,  6, 16],
       [ 1,  1, 10,  1],
       [ 5,  8, 19, 19],
       [ 9,  9,  2, 13],
       [ 6, 11, 13, 13]])

In [33]:
e[0,:]

array([17,  5, 19,  6])

In [34]:
e[-1,:]

array([ 6, 11, 13, 13])

In [35]:
e[1:-1,:]

array([[17, 13,  6, 16],
       [ 1,  1, 10,  1],
       [ 5,  8, 19, 19],
       [ 9,  9,  2, 13]])

In [36]:
e[:,2]

array([19,  6, 10, 19,  2, 13])

In [37]:
np.mean(e)

9.958333333333334

In [38]:
np.mean(e, axis = 1)

array([11.75, 13.  ,  3.25, 12.75,  8.25, 10.75])

In [39]:
np.mean(e, axis = 0)

array([ 9.16666667,  7.83333333, 11.5       , 11.33333333])

In [42]:
first_column = e[:,0]
first_column

array([17, 17,  1,  5,  9,  6])

In [ ]:
np.mean